version: '3.8'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 company_site.wsgi"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://company_user:company_pass@db:5432/company_db
      - DJANGO_SETTINGS_MODULE=company_site.settings
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=company_db
      - POSTGRES_USER=company_user
      - POSTGRES_PASSWORD=company_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: